config/routes.rb
Rails.application.routes.draw do

  namespace :integration do
    resources :apps
  end

  namespace :faturamento do
    namespace :saude_suplementar do
      resources :lotes
      resources :atendimentos
    end
  end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'atendimentos/statistics/count'   => 'atendimentos/statistics#count' 
  get 'atendimentos/statistics/prices'  => 'atendimentos/statistics#prices' 
  get 'atendimentos/statistics/medicos' => 'atendimentos/statistics#medicos' 

  root 'dashboard#index'
  

end

app/models/integration/lote.rb
class Integration::Lote
  include Mongoid::Document
  include Mongoid::Timestamps

  field :user_id, :type => Integer
  field :numero,  :type => Integer
  field :status,  :type => Boolean, default: true
  field :billed,  :type => Boolean, default: false

  field :xml,     :type => String
  field :pdf,     :type => String

  has_many :atendimentos, :class_name => 'Integration::Atendimento'

  # Faz o calculo do preço dos atendimentos
  #
  # @return [ String ]
  def valor
    self.atendimentos.sum(:valor_total)
  end
end

app/controllers/faturamento/saude_suplementar/atendimentos_controller.rb
class Faturamento::SaudeSuplementar::AtendimentosController < ApplicationController

  # GET Lista de atendimentos que não possui lote
  def index
    @atendimentos = Integration::Atendimento.where(:lote_id => {'$exists' => false}).page(page)
    @count        = Integration::Atendimento.where(:lote_id => {'$exists' => false}).count
  end
end

app/controllers/faturamento/saude_suplementar/lotes_controller.rb
class Faturamento::SaudeSuplementar::LotesController < ApplicationController

  # GET Lista de lotes gerados
  def index
    @lotes = Integration::Lote.order_by(:created_at => -1).page(page)
  end

  # GET cria um novo lote
  def new
    @atendimentos = Integration::Atendimento.where(:lote_id => {'$exists' => false}).page(page)
    @lote = Integration::Lote.new
  end

  # POST cria o lote
  def create
    p params.to_json
  end
end

app/helpers/faturamento/saude_suplementar/lote_helper.rb
module Faturamento::SaudeSuplementar::LoteHelper
end

app/views/faturamento/saude_suplementar/lotes/index.html.erb
<% title 'Saude Suplementar', 'lotes de faturamento' %>

<%= link_to new_faturamento_saude_suplementar_lote_path, class: 'btn btn-success m-r-5 m-b-5' do %>
  <span class="glyphicon glyphicon-plus"></span>
  Novo
<% end %>
<div class="row">
  <div class="col-md-12">
     <div class="panel panel-inverse">
      <div class="panel-heading">
        <div class="panel-heading-btn">
          <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand">
            <i class="fa fa-expand"></i>
          </a>
          <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse" data-original-title="" title="">
            <i class="fa fa-minus"></i>
          </a>
        </div>
        <h4 class="panel-title">Lotes</h4>
      </div>
      <div class="panel-body">
        <div class="table-responsive">
          <table 
            datatable=""
            id="data-lotes"
            class="table table-striped table-bordered table-center">

            <thead>
              <th>Numéro</th>
              <th>Data</th>
              <th>Status</th>
              <th>Atendimentos</th>
              <th>Valor</th>
              <th>Download</th>
            </thead>
            <tbody>
              <%= content_tag_for(:tr, @lotes) do |lote| %>
                <td><%= lote.numero %></td>
                <td><%= l(lote.created_at) %></td>
                <td><%= lote.status %></td>
                <td><%= lote.atendimentos.count %></td>
                <td><%= lote.valor %></td>
                <td>
                  <%= link_to '#', :class => 'btn btn-xs' do %>
                    <i class="fa fa-file-text-o"></i>
                  <% end %>

                  <%= link_to '#', :class => 'btn btn-xs' do %>
                    <i class="fa fa-file-pdf-o pdf-icon"></i>
                  <% end %>

                  <%= link_to '#', :class => 'btn btn-xs' do %>
                    <i class="fa fa-file-archive-o zip-icon"></i>
                  <% end %>
                </td>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/faturamento/saude_suplementar/lotes/new.html.erb
<% title 'Novo Lote', 'saude suplementar faturamento' %>

<div class="row" ng-controller="SaudeSuplementarLote" ng-init="action()">
  <div class="col-md-10">
    <div class="panel panel-inverse">
      <div class="panel-heading">
          <div class="progress progress-striped progress-sm active pull-right m-t-5">
              <div class="progress-bar progress-bar-success" style="width: {{selecteds.length}}%">{{selecteds.length}}%</div>
          </div>
          <h4 class="panel-title">Atendimentos</h4>
      </div>
      <div class="panel-body">
            <table
              id="data-lotes"
              class="table table-striped table-bordered table-center table-hover"
            >
              <thead>
                <th># </th>
                <th>ID</th>
                <th>Data</th>
                <th>Profissional</th>
                <th>Paciente</th>
                <th>Valor</th>
              </thead>
              <tbody>
                <tr class="pointer" ng-repeat="atendimento in atendimentos" ng-click="select(atendimento);">
                  <td>
                    <input 
                      type="checkbox"
                      value="{{atendimento.id}}"
                      ng-checked="isSelected(atendimento)"
                    />
                  </td>
                  <td>{{atendimento.id}}</td>
                  <td>{{atendimento.data}}</td>
                  <td>{{atendimento.paciente.nome}}</td>
                  <td>{{atendimento.profissional.nome}}</td>
                  <td>{{atendimento.valor_total}}</td>
                </tr>
              </tbody>
            </table>


          <paging
            class="small"
            scroll-top="true" 
            page="currentPage" 
            page-size="pageSize" 
            total="total"
            ul-class="pagination"
            active-class="active"
            paging-action="action(page)"
            pg-href="#page-{page}"
            disabled-class="disabled">  
      </div>
    </div>
  </div>
  <div class="col-md-2 col-sm-6 animated fadeIn fixed-scroll" ng-show="selecteds.length > 0">
    <div class="widget widget-stats bg-green">
      <div class="stats-icon"><i class="fa fa-usd"></i></div>
      <div class="stats-info">
        <h4>Valor do Lote</h4>
        <p>
          {{price}}
        </p> 
      </div>
    </div>
    <div class="">
      <button class="btn btn-lg btn-success pull-right">Gerar</button>
    </div>
  </div>
</div>