config/routes.rb
Rails.application.routes.draw do

  namespace :integration do
    resources :apps
  end

  namespace :faturamento do
    namespace :saude_suplementar do
      resources :lotes
      resources :atendimentos
    end
  end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'atendimentos/statistics/count'   => 'atendimentos/statistics#count' 
  get 'atendimentos/statistics/prices'  => 'atendimentos/statistics#prices' 
  get 'atendimentos/statistics/medicos' => 'atendimentos/statistics#medicos' 

  root 'dashboard#index'
  

end

app/views/layouts/default/_header.erb
<div id="header" class="header navbar navbar-default navbar-fixed-top">
  <!-- begin container-fluid -->
  <div class="container-fluid">
    <!-- begin mobile sidebar expand / collapse button -->
    <div class="navbar-header">
      <a href="index.html" class="navbar-brand"><span class="navbar-logo"></span> Gestão Clinica</a>
      <button type="button" class="navbar-toggle" data-click="sidebar-toggled">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <!-- end mobile sidebar expand / collapse button -->
    
    <!-- begin header navigation right -->
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="javascript:;" data-toggle="dropdown" class="dropdown-toggle f-s-14">
          <i class="fa fa-bell-o"></i>
          <span class="label">5</span>
        </a>
        <ul class="dropdown-menu media-list pull-right animated fadeInDown">
                        <li class="dropdown-header">Notifications (5)</li>
                        <li class="media">
                            <a href="javascript:;">
                                <div class="media-left"><i class="fa fa-bug media-object bg-red"></i></div>
                                <div class="media-body">
                                    <h6 class="media-heading">Server Error Reports</h6>
                                    <div class="text-muted f-s-11">3 minutes ago</div>
                                </div>
                            </a>
                        </li>
                        <li class="media">
                            <a href="javascript:;">
                                <div class="media-left"><img src="/assets/color-admin/img/user-1.jpg" class="media-object" alt="" /></div>
                                <div class="media-body">
                                    <h6 class="media-heading">John Smith</h6>
                                    <p>Quisque pulvinar tellus sit amet sem scelerisque tincidunt.</p>
                                    <div class="text-muted f-s-11">25 minutes ago</div>
                                </div>
                            </a>
                        </li>
                        <li class="media">
                            <a href="javascript:;">
                                <div class="media-left"><img src="/assets/color-admin/img/user-2.jpg" class="media-object" alt="" /></div>
                                <div class="media-body">
                                    <h6 class="media-heading">Olivia</h6>
                                    <p>Quisque pulvinar tellus sit amet sem scelerisque tincidunt.</p>
                                    <div class="text-muted f-s-11">35 minutes ago</div>
                                </div>
                            </a>
                        </li>
                        <li class="media">
                            <a href="javascript:;">
                                <div class="media-left"><i class="fa fa-plus media-object bg-green"></i></div>
                                <div class="media-body">
                                    <h6 class="media-heading"> New User Registered</h6>
                                    <div class="text-muted f-s-11">1 hour ago</div>
                                </div>
                            </a>
                        </li>
                        <li class="media">
                            <a href="javascript:;">
                                <div class="media-left"><i class="fa fa-envelope media-object bg-blue"></i></div>
                                <div class="media-body">
                                    <h6 class="media-heading"> New Email From John</h6>
                                    <div class="text-muted f-s-11">2 hour ago</div>
                                </div>
                            </a>
                        </li>
                        <li class="dropdown-footer text-center">
                            <a href="javascript:;">View more</a>
                        </li>
        </ul>
      </li>
      <li class="dropdown navbar-user">
        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
          <img src="/assets/color-admin/img/user-13.jpg" alt="" /> 
          <span class="hidden-xs"><%= @current_user.first_name %> <%= @current_user.last_name %></span> <b class="caret"></b>
        </a>
        <ul class="dropdown-menu animated fadeInLeft">
          <li class="arrow"></li>
          <li><a href="javascript:;">Edit Profile</a></li>
          <li><a href="javascript:;"><span class="badge badge-danger pull-right">2</span> Inbox</a></li>
          <li><a href="javascript:;">Calendar</a></li>
          <li><a href="javascript:;">Setting</a></li>
          <li class="divider"></li>
          <li><a href="javascript:;">Log Out</a></li>
        </ul>
      </li>
    </ul>
    <!-- end header navigation right -->
  </div>
  <!-- end container-fluid -->
</div>

app/views/layouts/default/_sidebar.erb
<div id="sidebar" class="sidebar">
  <!-- begin sidebar scrollbar -->
  <div data-scrollbar="true" data-height="100%">
    <!-- end sidebar user -->
    <!-- begin sidebar nav -->
    <ul class="nav">
      <li class="has-sub <%= menu_item_active(root_path) %>">
        <%= link_to root_path do %>
          <i class="fa fa-laptop"></i>
          <span>Dashboard</span>
        <% end %>
      </li>
      <li class="has-sub <%= menu_item_active(faturamento_saude_suplementar_lotes_path) %>">
        <a href="javascript:;">
          <b class="caret pull-right"></b>
          <i class="fa fa-usd"></i> 
          <span>Faturamento</span>
        </a>
        <ul class="sub-menu">
          <li class="<%= menu_item_active(faturamento_saude_suplementar_lotes_path) %>">
            <a href="<%= faturamento_saude_suplementar_lotes_path %>">
              Saude Suplementar
            </a>
          </li>
        </ul>
      </li>
      <li class="has-sub <%= menu_item_active(integration_apps_path) %>">
        <a href="javascript:;">
          <b class="caret pull-right"></b>
          <i class="fa fa-exchange"></i> 
          <span>Integrações</span>
        </a>
        <ul class="sub-menu">
          <li class="<%= menu_item_active(integration_apps_path) %>">
            <%= link_to integration_apps_path do %>
              <i class="fa fa-rocket"></i>
              <span>Aplicações</span>
            <% end %>
          </li>
        </ul>
      </li>
      <li><a href="javascript:;" class="sidebar-minify-btn" data-click="sidebar-minify"><i class="fa fa-angle-double-left"></i></a></li>
          <!-- end sidebar minify button -->
    </ul>
    <!-- end sidebar nav -->
  </div>
  <!-- end sidebar scrollbar -->
</div>
<div class="sidebar-bg"></div>